version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hello_spring_boot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hellodb
      MYSQL_USER: hellouser
      MYSQL_PASSWORD: hellopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
